### ISSUE TITLE
Volet Mon compte non visible

### ISSUE THREAD

**Issue by chayr** [philippedemaria/sacado#11]
Après avoir scrollé plus d'une page vers le bas, on ne voit plus le menu _Mon Compte_ apparaitre et on a l'impression que le bouton ne fonctionne pas

![image](https://user-images.githubusercontent.com/3321967/84791157-decbde00-afb7-11ea-911f-f4d7ad0b81c4.png)

**Comment by philippedemaria** [comment]
avec du CSS

.content_list::-webkit-scrollbar {
  width: 0px;
  height: 20px;
}
.content_list::-webkit-scrollbar-track {
  background-color: rgba(0, 0, 0, 0);
  border-radius: 10px;
}
.content_list::-webkit-scrollbar-thumb {
  background-color: rgba(0, 0, 0, 0.1);
  border-radius: 10px;
}
