### ISSUE TITLE
form.is_mark

### ISSUE THREAD

**Issue by chayr** [philippedemaria/sacado#17]
erreur dans le log pour `form.is_mark` et `form.modification`
![image](https://user-images.githubusercontent.com/3321967/85238964-f9a6b400-b3f6-11ea-8144-1bdea5455461.png)
![image](https://user-images.githubusercontent.com/3321967/85239096-b3058980-b3f7-11ea-9c66-d40331b25324.png)

`content_details.html` est inclus depuis `form_course`

![image](https://user-images.githubusercontent.com/3321967/85238854-738a6d80-b3f6-11ea-9e94-88950565b2e4.png)

form est un CourseForm appelé par create_course
![image](https://user-images.githubusercontent.com/3321967/85238891-9b79d100-b3f6-11ea-92d8-033c432184b3.png)

CourseForm est un ModelForm
![image](https://user-images.githubusercontent.com/3321967/85238901-a92f5680-b3f6-11ea-8142-ea5d4513a1e9.png)

mais il n'y a pas de champ `is_mark` ou `modification` dans Course
![image](https://user-images.githubusercontent.com/3321967/85238935-d24fe700-b3f6-11ea-8447-280b192a457b.png)

**Comment by philippedemaria** [comment]
ok !
