### ISSUE TITLE
Pas de champ correspondant à exercise.is_publish

### ISSUE THREAD

**Issue by chayr** [philippedemaria/sacado#19]
dans `detail_student.html`

![image](https://user-images.githubusercontent.com/3321967/87792958-32755580-c80a-11ea-9c32-5d85d3cc2630.png)

dans `parcours_tasks_and_publishes.html`

![image](https://user-images.githubusercontent.com/3321967/87793104-69e40200-c80a-11ea-83d0-0d65ccc1f273.png)

Modèle Exercise :
![image](https://user-images.githubusercontent.com/3321967/87793190-8b44ee00-c80a-11ea-90ba-35f6e6a9c288.png)

**Comment by philippedemaria** [comment]
Pour detail_student.html, certes exercise.is_publish ce n'est pas top car on crois que exercise a un attribut is_publish. En fait je recolle à exercise l'attibut de la relation avec son parcours via un dictionnaire. L'appel est dont exercise.is_publish sans pour autant appeler l'attribut.
Pour moi, il n'y a donc pas d'erreur.

**Comment by philippedemaria** [comment]
Pour parcours_tasks_and_publishes.html, il y a une erreur, que je répare.
