### ISSUE TITLE
404 ajax publish parcours depuis l'édition d'un parcours

### ISSUE THREAD

**Issue by chayr** [philippedemaria/sacado#4]
en cliquant sur le bouton du haut depuis l'édition d'un parcours

![image](https://user-images.githubusercontent.com/3321967/84606075-32c7ad00-ae68-11ea-9528-ffd9c8917b8b.png)

après il y a 2 boutons qui font la même chose sur la même page
![image](https://user-images.githubusercontent.com/3321967/84606096-60145b00-ae68-11ea-96b6-42a2262ee227.png)
si on fait _Annuler_ les modifications d'un des boutons sont prises en compte (ajax) tant que l'autre non...

**Comment by philippedemaria** [comment]
ok réglé
