### ISSUE TITLE
2 fichiers js ckeditor ne chargent pas, erreur 404

### ISSUE THREAD

**Issue by chayr** [philippedemaria/sacado#7]
depuis 
https://sacado.xyz/sendmail/

![image](https://user-images.githubusercontent.com/3321967/84789411-d1155900-afb5-11ea-9c89-9b056ae1670e.png)

**Comment by philippedemaria** [comment]
![2020-06-18_10h22_14](https://user-images.githubusercontent.com/51360715/85003041-9514fc00-b14d-11ea-8a37-ff4f9097fa19.png)
ince il charge chez moi !

**Comment by philippedemaria** [comment]
![2020-06-18_10h33_17](https://user-images.githubusercontent.com/51360715/85004156-22a51b80-b14f-11ea-8d9a-e685ffe43355.png)
ok sur le serveur
